export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'The first blog',
        author: 'author1',
        dateStr: 'May 12nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog1.html',
      },
      {
        title: 'The second blog',
        author: 'author2',
        dateStr: 'May 2nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog2.html',
      },
      {
        title: 'The third blog',
        author: 'author3',
        dateStr: 'April 25th，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog3.html',
      },
      {
        title: 'The forth blog',
        author: 'author4',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog4.html',
      },
      {
        title: 'The fifth blog',
        author: 'author5',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog5.html',
      },
      {
        title: 'The sixth blog',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog6.html',
      },
      {
        title: 'The seventh blog',
        author: 'author7',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog7.html',
      },
    ],
  },
  'zh-cn': {
    barText: '翡翠美文',
    postsTitle: '所有文章',
    list: [
      {
        title: '翡翠历史渊源',
        author: '钱猛',
        dateStr: 'May 12nd，2018',
        desc: '从古至今，翡翠的历史渊源剖析',
        link: '/zh-cn/blog/blog1.html',
      },
      {
        title: '四大翡翠批发地',
        author: '钱猛',
        dateStr: 'May 23nd，2018',
        desc: '中国四大翡翠批发地，缅甸、四会。。。',
        link: '/zh-cn/blog/blog2.html',
      },
      {
        title: '关于直播卖翡翠',
        author: '钱猛',
        dateStr: 'April 25th，2018',
        desc: '全面直播带货，关于翡翠的直播带货突然崛起',
        link: '/zh-cn/blog/blog3.html',
      },
      {
        title: '翡翠价值评估',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: '如何判别翡翠的好坏，价值度',
        link: '/zh-cn/blog/blog4.html',
      },
      {
        title: '翡翠种类详解',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: '众多翡翠，眼花缭乱，分类分析',
        link: '/zh-cn/blog/blog5.html',
      },
      {
        title: '翡翠制作方法',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: '精美的翡翠是如何制作的',
        link: '/zh-cn/blog/blog6.html',
      }
    ],
  },
};
